controller:
  JCasC:
    configScripts:
      welcome-job: |
        jobs:
          - script: >
              job('hello-world') {
                description('A simple hello world job')
                steps {
                  shell('echo Hello World!')
                }
              }
