name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Format Check
        run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6
      
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli jq
      
      - name: Assume IAM Role
        id: assume_role
        run: |
          ROLE_ARN="arn:aws:iam::145023129007:role/GithubActionsRole"
          WEB_IDENTITY_TOKEN="${GITHUB_ENV}/GITHUB_TOKEN" # Use the GitHub token directly
          CREDS=$(aws sts assume-role-with-web-identity \
            --role-arn $ROLE_ARN \
            --role-session-name GitHubActionsSession \
            --web-identity-token $WEB_IDENTITY_TOKEN \
            --output json)
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .Credentials.AccessKeyId)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .Credentials.SecretAccessKey)" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Credentials.SessionToken)" >> $GITHUB_ENV
      
      - name: Terraform Plan
        env:
          AWS_REGION: us-east-1
        run: |
          terraform init
          terraform plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve
